{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53807107.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53807107"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "Also, even after setting `use_cache` to true, which means it does load the model from `~/gazebo`, it seems it\u2019s not able to load the textures:\n\n![](data/bitbucket.org/repo/jgXqbo/images/3038247860-Screenshot_from_2019-09-08_22-20-15.png)\nI have the API key loaded, for all that matters. Manually trying to open the png images seem to not work as well, so I suppose the download is somehow failing?", "markup": "markdown", "html": "<p>Also, even after setting <code>use_cache</code> to true, which means it does load the model from <code>~/gazebo</code>, it seems it\u2019s not able to load the textures:</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/jgXqbo/images/3038247860-Screenshot_from_2019-09-08_22-20-15.png\" />\nI have the API key loaded, for all that matters. Manually trying to open the png images seem to not work as well, so I suppose the download is somehow failing?</p>", "type": "rendered"}, "created_on": "2019-09-08T21:21:59.810609+00:00", "user": {"display_name": "Nuno Marques", "uuid": "{a7356a80-a26a-4ab7-af5b-494fe038a1c7}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D"}, "html": {"href": "https://bitbucket.org/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52/20fd74f9-d763-4f0e-b57f-c4570327e595/128"}}, "nickname": "TSC21", "type": "user", "account_id": "557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52"}, "updated_on": null, "type": "issue_comment", "id": 53807107}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53822951.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53822951"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "You can try calling its API directly using the example [here](https://developers.google.com/maps/documentation/maps-static/get-api-key)\n\nI did a quick test got this msg:\n\n```\nThe Google Maps Platform server rejected your request. You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable.Learn more at https://developers.google.com/maps/gmp-get-started\n```\n\nNot sure if this is the case for you. Enabling billing was not a requirement before at the time when this plugin was implemented. If the cause of the issue is the same for you, we should update the tutorial.", "markup": "markdown", "html": "<p>You can try calling its API directly using the example <a data-is-external-link=\"true\" href=\"https://developers.google.com/maps/documentation/maps-static/get-api-key\" rel=\"nofollow\">here</a></p>\n<p>I did a quick test got this msg:</p>\n<div class=\"codehilite\"><pre><span></span>The Google Maps Platform server rejected your request. You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable.Learn more at https://developers.google.com/maps/gmp-get-started\n</pre></div>\n\n\n<p>Not sure if this is the case for you. Enabling billing was not a requirement before at the time when this plugin was implemented. If the cause of the issue is the same for you, we should update the tutorial.</p>", "type": "rendered"}, "created_on": "2019-09-09T17:55:10.058657+00:00", "user": {"display_name": "Ian Chen", "uuid": "{eaa6fca5-6deb-43f6-907f-971c144735dd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D"}, "html": {"href": "https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5/1e4adcdf-1946-4280-9aea-eb5f15a7f912/128"}}, "nickname": "Ian Chen", "type": "user", "account_id": "557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5"}, "updated_on": null, "type": "issue_comment", "id": 53822951}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53823070.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53823070"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "well actually, it could be a different problem from looking at your error msg. Is the model created in `/tmp/` and are you able to view the textures in `/tmp/<model_name>/materials/textures/`?", "markup": "markdown", "html": "<p>well actually, it could be a different problem from looking at your error msg. Is the model created in <code>/tmp/</code> and are you able to view the textures in <code>/tmp/&lt;model_name&gt;/materials/textures/</code>?</p>", "type": "rendered"}, "created_on": "2019-09-09T18:00:35.260859+00:00", "user": {"display_name": "Ian Chen", "uuid": "{eaa6fca5-6deb-43f6-907f-971c144735dd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D"}, "html": {"href": "https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5/1e4adcdf-1946-4280-9aea-eb5f15a7f912/128"}}, "nickname": "Ian Chen", "type": "user", "account_id": "557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5"}, "updated_on": null, "type": "issue_comment", "id": 53823070}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53824903.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53824903"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "I am able to access the model in `/tmp/`, though I can't open any of the download `png`files in that folder.", "markup": "markdown", "html": "<p>I am able to access the model in <code>/tmp/</code>, though I can't open any of the download <code>png</code>files in that folder.</p>", "type": "rendered"}, "created_on": "2019-09-09T20:39:21.863684+00:00", "user": {"display_name": "Nuno Marques", "uuid": "{a7356a80-a26a-4ab7-af5b-494fe038a1c7}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D"}, "html": {"href": "https://bitbucket.org/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52/20fd74f9-d763-4f0e-b57f-c4570327e595/128"}}, "nickname": "TSC21", "type": "user", "account_id": "557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52"}, "updated_on": null, "type": "issue_comment", "id": 53824903}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53824930.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53824930"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "@{557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5} but basically I am getting two issues: the one I report on the issue description, which it needs a solution on code so to solve the cross-device link problem, and the on the comment, which I am not sure what\u2019s causing it.", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5\">@Ian Chen</span> but basically I am getting two issues: the one I report on the issue description, which it needs a solution on code so to solve the cross-device link problem, and the on the comment, which I am not sure what\u2019s causing it.</p>", "type": "rendered"}, "created_on": "2019-09-09T20:41:58.872894+00:00", "user": {"display_name": "Nuno Marques", "uuid": "{a7356a80-a26a-4ab7-af5b-494fe038a1c7}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D"}, "html": {"href": "https://bitbucket.org/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52/20fd74f9-d763-4f0e-b57f-c4570327e595/128"}}, "nickname": "TSC21", "type": "user", "account_id": "557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52"}, "updated_on": null, "type": "issue_comment", "id": 53824930}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53859529.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53859529"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "@{557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5} @{557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8} can I have your insights here please? This is currently a blocker and making the plugin unusable. Thank you", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5\">@Ian Chen</span> <span class=\"ap-mention\" data-atlassian-id=\"557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8\">@Louise Poubel</span> can I have your insights here please? This is currently a blocker and making the plugin unusable. Thank you</p>", "type": "rendered"}, "created_on": "2019-09-11T10:21:54.997118+00:00", "user": {"display_name": "Nuno Marques", "uuid": "{a7356a80-a26a-4ab7-af5b-494fe038a1c7}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D"}, "html": {"href": "https://bitbucket.org/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52/20fd74f9-d763-4f0e-b57f-c4570327e595/128"}}, "nickname": "TSC21", "type": "user", "account_id": "557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52"}, "updated_on": null, "type": "issue_comment", "id": 53859529}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53865958.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53865958"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "> I am able to access the model in `/tmp/`, though I can't open any of the download `png`files in that folder.\n\ncould you try calling the api directly from a browser using this example and see if you\u2019re able to get the image?\n\n```\nhttps://maps.googleapis.com/maps/api/staticmap?center=40.714%2c%20-73.998&zoom=12&size=400x400&key=YOUR_API_KEY \n```\n\nAs for the boost rename error, doing a try catch sound good. In the mean time to workaround the problem, you may have to just manually copy the model in `/tmp` to your `~/.gazebo/models` folder and insert it from the `Insert` tab.", "markup": "markdown", "html": "<blockquote>\n<p>I am able to access the model in <code>/tmp/</code>, though I can't open any of the download <code>png</code>files in that folder.</p>\n</blockquote>\n<p>could you try calling the api directly from a browser using this example and see if you\u2019re able to get the image?</p>\n<div class=\"codehilite\"><pre><span></span>https://maps.googleapis.com/maps/api/staticmap?center=40.714%2c%20-73.998&amp;zoom=12&amp;size=400x400&amp;key=YOUR_API_KEY \n</pre></div>\n\n\n<p>As for the boost rename error, doing a try catch sound good. In the mean time to workaround the problem, you may have to just manually copy the model in <code>/tmp</code> to your <code>~/.gazebo/models</code> folder and insert it from the <code>Insert</code> tab.</p>", "type": "rendered"}, "created_on": "2019-09-11T17:34:21.804480+00:00", "user": {"display_name": "Ian Chen", "uuid": "{eaa6fca5-6deb-43f6-907f-971c144735dd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D"}, "html": {"href": "https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5/1e4adcdf-1946-4280-9aea-eb5f15a7f912/128"}}, "nickname": "Ian Chen", "type": "user", "account_id": "557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5"}, "updated_on": null, "type": "issue_comment", "id": 53865958}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53883495.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53883495"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "@{557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5} actually it now does works. The problem is that I didn\u2019t have the API activated. Now it works correctly.\n\nSo now we are just missing the fix to the `boost::filesystem::rename` error. Is that something you can take care of? Thanks.", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5\">@Ian Chen</span> actually it now does works. The problem is that I didn\u2019t have the API activated. Now it works correctly.</p>\n<p>So now we are just missing the fix to the <code>boost::filesystem::rename</code> error. Is that something you can take care of? Thanks.</p>", "type": "rendered"}, "created_on": "2019-09-12T19:49:02.996681+00:00", "user": {"display_name": "Nuno Marques", "uuid": "{a7356a80-a26a-4ab7-af5b-494fe038a1c7}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D"}, "html": {"href": "https://bitbucket.org/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52/20fd74f9-d763-4f0e-b57f-c4570327e595/128"}}, "nickname": "TSC21", "type": "user", "account_id": "557058:2ae57099-6545-4ef4-8e48-3cd5f87b7f52"}, "updated_on": null, "type": "issue_comment", "id": 53883495}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657/comments/53885311.json"}, "html": {"href": "#!/osrf/gazebo/issues/2657#comment-53885311"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2657.json"}}, "type": "issue", "id": 2657, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "StaticMapPlugin: boost::filesystem::rename: Invalid cross-device link: \"/tmp/<model_name>\", \"/home/.../.gazebo/models/<model_name>\""}, "content": {"raw": "pull request #3123", "markup": "markdown", "html": "<p><a href=\"#!/osrf/gazebo/pull-requests/3123/fix-moving-model-files-in-staticmapplugin\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #3123</a></p>", "type": "rendered"}, "created_on": "2019-09-13T00:15:21.940134+00:00", "user": {"display_name": "Ian Chen", "uuid": "{eaa6fca5-6deb-43f6-907f-971c144735dd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D"}, "html": {"href": "https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5/1e4adcdf-1946-4280-9aea-eb5f15a7f912/128"}}, "nickname": "Ian Chen", "type": "user", "account_id": "557058:10b01d41-a2e9-4a41-a907-e6e2f03b6cd5"}, "updated_on": null, "type": "issue_comment", "id": 53885311}], "page": 1, "size": 9}