{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/1180/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/1180.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1180/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/1180/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/1180/seg-fault-during-material-destructor"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1180/vote"}}, "reporter": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "title": "Seg-fault during Material destructor", "component": {"name": "common", "links": {"self": {"href": "data/repositories/osrf/gazebo/components/138866.json"}}}, "votes": 0, "watches": 3, "content": {"raw": "As mentioned in [release-tools #20](https://bitbucket.org/osrf/release-tools/issue/20/jenkins-misses-some-testing-seg-faults), there are some tests that seg-fault so late that Jenkins thinks that they passed. Specifically, the INTEGRATION_concave_mesh test has been seg-faulting since pull request #1066. Through testing, I have identified the tests involving submeshes (ie. `--gtest_filter=\"*SubmeshCollisionTest*\"` or `--gtest_filter=\"*SubmeshNoCollisionTest*\"`).\r\n\r\nNote that it is [not listed in the list of failing tests](http://build.osrfoundation.org/job/gazebo-default-devel-precise-amd64-gpu-nvidia/717/testReport/), but it is shown as seg-faulting in the\r\n[console output](http://build.osrfoundation.org/job/gazebo-default-devel-precise-amd64-gpu-nvidia/717/consoleFull):\r\n~~~\r\n145: [----------] 9 tests from PhysicsEngines/ConcaveMeshTest (36369 ms total)\r\n145: \r\n145: [----------] Global test environment tear-down\r\n145: [==========] 9 tests from 1 test case ran. (36369 ms total)\r\n145: [  PASSED  ] 9 tests.\r\n145: \u001b[0m\r\n  5/108 Test #145: INTEGRATION_concave_mesh .....................***Exception: SegFault 58.20 sec\r\ntest 146\r\n        Start 146: check_INTEGRATION_concave_mesh\r\n\r\n146: Test command: /var/lib/jenkins/workspace/gazebo-default-devel-precise-amd64-gpu-nvidia/gazebo/tools/check_test_ran.py \"/var/lib/jenkins/workspace/gazebo-default-devel-precise-amd64-gpu-nvidia/build/test_results/INTEGRATION_concave_mesh.xml\"\r\n146: Test timeout computed to be: 9.99988e+06\r\n146: Checking for test results in /var/lib/jenkins/workspace/gazebo-default-devel-precise-amd64-gpu-nvidia/build/test_results/INTEGRATION_concave_mesh.xml\r\n  6/108 Test #146: check_INTEGRATION_concave_mesh ...............   Passed    0.02 sec\r\n\r\n~~~\r\n\r\nHere's a backtrace that implicates the Material destructor:\r\n~~~\r\n(gdb) bt\r\n#0  0x00007ffff46a6f77 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56\r\n#1  0x00007ffff46aa5e8 in __GI_abort () at abort.c:90\r\n#2  0x00007ffff46e44fb in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff47f8240 \"*** Error in `%s': %s: 0x%s ***\\n\")\r\n    at ../sysdeps/unix/sysv/linux/libc_fatal.c:199\r\n#3  0x00007ffff46ef4c6 in malloc_printerr (action=3, str=0x7ffff47f41e8 \"corrupted double-linked list\", ptr=<optimized out>) at malloc.c:4923\r\n#4  0x00007ffff46f0cb9 in _int_free (av=0x7fffcc000020, p=0x7fffccc999e0, have_lock=0) at malloc.c:3933\r\n#5  0x00007ffff7b87145 in ~basic_string (this=0x7fffccc998c0, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/basic_string.h:539\r\n#6  gazebo::common::Material::~Material (this=0x7fffccc998b0, __in_chrg=<optimized out>)\r\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Material.cc:65\r\n#7  0x00007ffff7b871f9 in gazebo::common::Material::~Material (this=0x7fffccc998b0, __in_chrg=<optimized out>)\r\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Material.cc:68\r\n#8  0x00007ffff7b87496 in gazebo::common::Mesh::~Mesh (this=0x7fffccaccaf0, __in_chrg=<optimized out>)\r\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Mesh.cc:54\r\n#9  0x00007ffff7b87559 in gazebo::common::Mesh::~Mesh (this=0x7fffccaccaf0, __in_chrg=<optimized out>)\r\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Mesh.cc:59\r\n#10 0x00007ffff7b8ba3f in gazebo::common::MeshManager::~MeshManager (\r\n    this=0x7ffff78fb9e0 <SingletonT<gazebo::common::MeshManager>::GetInstance()::t>, __in_chrg=<optimized out>)\r\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/MeshManager.cc:79\r\n#11 0x00007ffff46ac071 in __run_exit_handlers (status=0, listp=0x7ffff4a316a8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true)\r\n    at exit.c:77\r\n#12 0x00007ffff46ac0f5 in __GI_exit (status=<optimized out>) at exit.c:99\r\n#13 0x00007ffff4691dec in __libc_start_main (main=0x412ba0 <main(int, char**)>, argc=2, ubp_av=0x7fffffffda78, init=<optimized out>, \r\n    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda68) at libc-start.c:294\r\n#14 0x0000000000415ced in _start ()\r\n(gdb)\r\n~~~\r\n@iche033 @chapulina ", "markup": "markdown", "html": "<p>As mentioned in <a data-is-external-link=\"true\" href=\"https://bitbucket.org/osrf/release-tools/issue/20/jenkins-misses-some-testing-seg-faults\" rel=\"nofollow\">release-tools #20</a>, there are some tests that seg-fault so late that Jenkins thinks that they passed. Specifically, the INTEGRATION_concave_mesh test has been seg-faulting since <a href=\"#!/osrf/gazebo/pull-requests/1066/share-vertices-when-loading-a-collada-mesh\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #1066</a>. Through testing, I have identified the tests involving submeshes (ie. <code>--gtest_filter=\"*SubmeshCollisionTest*\"</code> or <code>--gtest_filter=\"*SubmeshNoCollisionTest*\"</code>).</p>\n<p>Note that it is <a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/gazebo-default-devel-precise-amd64-gpu-nvidia/717/testReport/\" rel=\"nofollow\">not listed in the list of failing tests</a>, but it is shown as seg-faulting in the\n<a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/gazebo-default-devel-precise-amd64-gpu-nvidia/717/consoleFull\" rel=\"nofollow\">console output</a>:</p>\n<div class=\"codehilite\"><pre><span></span>145: [----------] 9 tests from PhysicsEngines/ConcaveMeshTest (36369 ms total)\n145: \n145: [----------] Global test environment tear-down\n145: [==========] 9 tests from 1 test case ran. (36369 ms total)\n145: [  PASSED  ] 9 tests.\n145: \u001b[0m\n  5/108 Test #145: INTEGRATION_concave_mesh .....................***Exception: SegFault 58.20 sec\ntest 146\n        Start 146: check_INTEGRATION_concave_mesh\n\n146: Test command: /var/lib/jenkins/workspace/gazebo-default-devel-precise-amd64-gpu-nvidia/gazebo/tools/check_test_ran.py &quot;/var/lib/jenkins/workspace/gazebo-default-devel-precise-amd64-gpu-nvidia/build/test_results/INTEGRATION_concave_mesh.xml&quot;\n146: Test timeout computed to be: 9.99988e+06\n146: Checking for test results in /var/lib/jenkins/workspace/gazebo-default-devel-precise-amd64-gpu-nvidia/build/test_results/INTEGRATION_concave_mesh.xml\n  6/108 Test #146: check_INTEGRATION_concave_mesh ...............   Passed    0.02 sec\n</pre></div>\n\n\n<p>Here's a backtrace that implicates the Material destructor:</p>\n<div class=\"codehilite\"><pre><span></span>(gdb) bt\n#0  0x00007ffff46a6f77 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56\n#1  0x00007ffff46aa5e8 in __GI_abort () at abort.c:90\n#2  0x00007ffff46e44fb in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff47f8240 &quot;*** Error in `%s&#39;: %s: 0x%s ***\\n&quot;)\n    at ../sysdeps/unix/sysv/linux/libc_fatal.c:199\n#3  0x00007ffff46ef4c6 in malloc_printerr (action=3, str=0x7ffff47f41e8 &quot;corrupted double-linked list&quot;, ptr=&lt;optimized out&gt;) at malloc.c:4923\n#4  0x00007ffff46f0cb9 in _int_free (av=0x7fffcc000020, p=0x7fffccc999e0, have_lock=0) at malloc.c:3933\n#5  0x00007ffff7b87145 in ~basic_string (this=0x7fffccc998c0, __in_chrg=&lt;optimized out&gt;) at /usr/include/c++/4.8/bits/basic_string.h:539\n#6  gazebo::common::Material::~Material (this=0x7fffccc998b0, __in_chrg=&lt;optimized out&gt;)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Material.cc:65\n#7  0x00007ffff7b871f9 in gazebo::common::Material::~Material (this=0x7fffccc998b0, __in_chrg=&lt;optimized out&gt;)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Material.cc:68\n#8  0x00007ffff7b87496 in gazebo::common::Mesh::~Mesh (this=0x7fffccaccaf0, __in_chrg=&lt;optimized out&gt;)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Mesh.cc:54\n#9  0x00007ffff7b87559 in gazebo::common::Mesh::~Mesh (this=0x7fffccaccaf0, __in_chrg=&lt;optimized out&gt;)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/Mesh.cc:59\n#10 0x00007ffff7b8ba3f in gazebo::common::MeshManager::~MeshManager (\n    this=0x7ffff78fb9e0 &lt;SingletonT&lt;gazebo::common::MeshManager&gt;::GetInstance()::t&gt;, __in_chrg=&lt;optimized out&gt;)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/common/MeshManager.cc:79\n#11 0x00007ffff46ac071 in __run_exit_handlers (status=0, listp=0x7ffff4a316a8 &lt;__exit_funcs&gt;, run_list_atexit=run_list_atexit@entry=true)\n    at exit.c:77\n#12 0x00007ffff46ac0f5 in __GI_exit (status=&lt;optimized out&gt;) at exit.c:99\n#13 0x00007ffff4691dec in __libc_start_main (main=0x412ba0 &lt;main(int, char**)&gt;, argc=2, ubp_av=0x7fffffffda78, init=&lt;optimized out&gt;, \n    fini=&lt;optimized out&gt;, rtld_fini=&lt;optimized out&gt;, stack_end=0x7fffffffda68) at libc-start.c:294\n#14 0x0000000000415ced in _start ()\n(gdb)\n</pre></div>\n\n\n<p>@iche033 @chapulina </p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2014-05-07T01:01:15.784581+00:00", "milestone": null, "updated_on": "2016-09-14T19:43:40.262514+00:00", "type": "issue", "id": 1180}