{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/1236/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/1236.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1236/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/1236/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/1236/ogre-error"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1236/vote"}}, "reporter": {"display_name": "Andrei Haidu", "uuid": "{825ae8d9-4737-437d-9090-c0b932f32bf2}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B825ae8d9-4737-437d-9090-c0b932f32bf2%7D"}, "html": {"href": "https://bitbucket.org/%7B825ae8d9-4737-437d-9090-c0b932f32bf2%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1a5e83c62729680f092d723cd0bf4c57d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsAH-4.png"}}, "nickname": "ahaidu", "type": "user", "account_id": "557058:7ed02d0b-401c-4f0c-8500-f87172d5477d"}, "title": "OGRE error", "component": {"name": "rendering", "links": {"self": {"href": "data/repositories/osrf/gazebo/components/122881.json"}}}, "votes": 0, "watches": 2, "content": {"raw": "Hi,\r\n\r\nFor a while now I get this ogre error during the simulations. The problem is I cannot reproduce it all the time. I used to get them at least from version 2.0 and now I am running default branch (4.0). Here is the error:\r\n\r\n```\r\n\r\ngzclient: /build/buildd/ogre-1.7.4+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && \"The minimum corner of the box must be less than or equal to maximum corner\"' failed.\r\n```\r\n\r\nIt usually happens when I change the visualization type, such as transparency, contact/collision visualization and afterwards I move around the scene. Or when when the objects accumulate huge forces and fly far away from the origin.\r\n", "markup": "markdown", "html": "<p>Hi,</p>\n<p>For a while now I get this ogre error during the simulations. The problem is I cannot reproduce it all the time. I used to get them at least from version 2.0 and now I am running default branch (4.0). Here is the error:</p>\n<div class=\"codehilite\"><pre><span></span>gzclient: /build/buildd/ogre-1.7.4+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&amp;, const Ogre::Vector3&amp;): Assertion `(min.x &lt;= max.x &amp;&amp; min.y &lt;= max.y &amp;&amp; min.z &lt;= max.z) &amp;&amp; &quot;The minimum corner of the box must be less than or equal to maximum corner&quot;&#39; failed.\n</pre></div>\n\n\n<p>It usually happens when I change the visualization type, such as transparency, contact/collision visualization and afterwards I move around the scene. Or when when the objects accumulate huge forces and fly far away from the origin.</p>", "type": "rendered"}, "assignee": null, "state": "new", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2014-07-25T13:07:14.245212+00:00", "milestone": null, "updated_on": "2016-09-14T19:23:09.989549+00:00", "type": "issue", "id": 1236}