{"priority": "critical", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/1676/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/1676.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1676/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/1676/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/1676/gzclient-shutdown-boost-exception"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1676/vote"}}, "reporter": {"display_name": "Nate Koenig", "uuid": "{c862cdd9-fcc8-4419-9fc7-e20db14b8fcb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D"}, "html": {"href": "https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:095b1e12-74ed-4e20-b44f-2f0745b616e0/ca24bb11-4787-4b14-a20d-d91835e9bde2/128"}}, "nickname": "Nathan Koenig", "type": "user", "account_id": "557058:095b1e12-74ed-4e20-b44f-2f0745b616e0"}, "title": "Gzclient shutdown boost exception", "component": null, "votes": 1, "watches": 2, "content": {"raw": "I see this error occasionally when closing Gazebo:\r\n\r\n```\r\n#!c++\r\n\r\nterminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'\r\n  what():  boost thread: trying joining itself: Resource deadlock avoided\r\n\r\n```\r\n\r\nI believe it's somewhere in the client.", "markup": "markdown", "html": "<p>I see this error occasionally when closing Gazebo:</p>\n<div class=\"codehilite language-c++\"><pre><span></span><span class=\"n\">terminate</span> <span class=\"n\">called</span> <span class=\"n\">after</span> <span class=\"n\">throwing</span> <span class=\"n\">an</span> <span class=\"n\">instance</span> <span class=\"n\">of</span> <span class=\"err\">&#39;</span><span class=\"n\">boost</span><span class=\"o\">::</span><span class=\"n\">exception_detail</span><span class=\"o\">::</span><span class=\"n\">clone_impl</span><span class=\"o\">&lt;</span><span class=\"n\">boost</span><span class=\"o\">::</span><span class=\"n\">exception_detail</span><span class=\"o\">::</span><span class=\"n\">error_info_injector</span><span class=\"o\">&lt;</span><span class=\"n\">boost</span><span class=\"o\">::</span><span class=\"n\">thread_resource_error</span><span class=\"o\">&gt;</span> <span class=\"o\">&gt;</span><span class=\"err\">&#39;</span>\n  <span class=\"n\">what</span><span class=\"p\">()</span><span class=\"o\">:</span>  <span class=\"n\">boost</span> <span class=\"kr\">thread</span><span class=\"o\">:</span> <span class=\"n\">trying</span> <span class=\"n\">joining</span> <span class=\"nl\">itself</span><span class=\"p\">:</span> <span class=\"n\">Resource</span> <span class=\"n\">deadlock</span> <span class=\"n\">avoided</span>\n</pre></div>\n\n\n<p>I believe it's somewhere in the client.</p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": {"name": "6.0", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/170782.json"}}}, "edited_on": null, "created_on": "2015-07-24T16:15:46.636156+00:00", "milestone": null, "updated_on": "2016-12-16T14:41:51.588837+00:00", "type": "issue", "id": 1676}