{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/2690/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/2690.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/2690/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/2690/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/2690/libgazebo9-dev-deb-package-not-correctly"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/2690/vote"}}, "reporter": {"display_name": "Silvio Traversaro", "uuid": "{34f404cb-5642-4f27-a032-e04c7143d776}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D"}, "html": {"href": "https://bitbucket.org/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:e1c3e6a0-9a64-4e5f-a668-feebc191c5b6/578caaa1-056c-45a2-8bf9-bee94c3bebef/128"}}, "nickname": "traversaro", "type": "user", "account_id": "557058:e1c3e6a0-9a64-4e5f-a668-feebc191c5b6"}, "title": "libgazebo9-dev deb package not correctly installing on Ubuntu 18.04 due to release 9.12", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Congrats to all the team for the Gazebo 11 release!\r\n\r\nIn other news, we noticed some failures in our Nightly jobs that use Gazebo 9, in particular the error is:\r\n\r\n```\r\nReading package lists...\r\nBuilding dependency tree...\r\nReading state information...\r\nSome packages could not be installed. This may mean that you have\r\nrequested an impossible situation or if you are using the unstable\r\ndistribution that some required packages have not yet been created\r\nor been moved out of Incoming.\r\nThe following information may help to resolve the situation:\r\nThe following packages have unmet dependencies:\r\n libgazebo9-dev : Depends: gazebo9-common \\(= 9.11.0-1~bionic\\) but it is not going to be installed\r\n Depends: gazebo9-plugin-base \\(= 9.11.0-1~bionic\\) but it is not going to be installed\r\nE: Unable to correct problems, you have held broken packages.\r\n\\##\\[error\\]Process completed with exit code 100.\r\n```\r\n\r\n\u200c\r\n\r\nI tried to restart the job, but the error seems to be persistent. I also reproduce it locally, and it seems that the problem is that `libgazebo9-dev` version is still 9.11, while `gazebo9-common` and `gazebo9-plugin-base` were updated to 9.12 .\r\n\r\nFull link to the failing job: [https://github.com/robotology/gazebo-yarp-plugins/runs/420659425](https://github.com/robotology/gazebo-yarp-plugins/runs/420659425)\r\n\r\n\u200c\r\n\r\ncc @{557058:155a32e2-420c-4d50-98e0-0e722f63f906}", "markup": "markdown", "html": "<p>Congrats to all the team for the Gazebo 11 release!</p>\n<p>In other news, we noticed some failures in our Nightly jobs that use Gazebo 9, in particular the error is:</p>\n<div class=\"codehilite\"><pre><span></span>Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\nThe following packages have unmet dependencies:\n libgazebo9-dev : Depends: gazebo9-common \\(= 9.11.0-1~bionic\\) but it is not going to be installed\n Depends: gazebo9-plugin-base \\(= 9.11.0-1~bionic\\) but it is not going to be installed\nE: Unable to correct problems, you have held broken packages.\n\\##\\[error\\]Process completed with exit code 100.\n</pre></div>\n\n\n<p>\u200c</p>\n<p>I tried to restart the job, but the error seems to be persistent. I also reproduce it locally, and it seems that the problem is that <code>libgazebo9-dev</code> version is still 9.11, while <code>gazebo9-common</code> and <code>gazebo9-plugin-base</code> were updated to 9.12 .</p>\n<p>Full link to the failing job: <a data-is-external-link=\"true\" href=\"https://github.com/robotology/gazebo-yarp-plugins/runs/420659425\" rel=\"nofollow\">https://github.com/robotology/gazebo-yarp-plugins/runs/420659425</a></p>\n<p>\u200c</p>\n<p>cc <span class=\"ap-mention\" data-atlassian-id=\"557058:155a32e2-420c-4d50-98e0-0e722f63f906\">@Jose Luis Rivero</span></p>", "type": "rendered"}, "assignee": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2020-02-01T09:21:30.074638+00:00", "milestone": null, "updated_on": "2020-02-03T18:36:03.189798+00:00", "type": "issue", "id": 2690}