{"priority": "trivial", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/601/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/601.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/601/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/601/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/601/running-gazebo-from-a-non-existent"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/601/vote"}}, "reporter": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "title": "Running gazebo from a non-existent directory throws exception", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I just happened to run `gazebo` from a directory that I had deleted in another shell, and go this:\r\n\r\n    terminate called after throwing an instance of 'boost::filesystem3::filesystem_error'\r\n    what():  boost::filesystem::current_path: No such file or directory\r\n\r\nDefinitely a minor thing, but it ought to be possible to work around that.", "markup": "markdown", "html": "<p>I just happened to run <code>gazebo</code> from a directory that I had deleted in another shell, and go this:</p>\n<div class=\"codehilite\"><pre><span></span>terminate called after throwing an instance of &#39;boost::filesystem3::filesystem_error&#39;\nwhat():  boost::filesystem::current_path: No such file or directory\n</pre></div>\n\n\n<p>Definitely a minor thing, but it ought to be possible to work around that.</p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2013-03-22T17:50:24.484351+00:00", "milestone": null, "updated_on": "2016-09-14T19:43:50.471001+00:00", "type": "issue", "id": 601}