{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/631/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/631.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/631/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/631/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/631/using-tmp-gz_modeltargz-is-not-friendly"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/631/vote"}}, "reporter": {"display_name": "John Hoare", "uuid": "{f2fb0aad-9933-4b16-a710-d9fe1486032f}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bf2fb0aad-9933-4b16-a710-d9fe1486032f%7D"}, "html": {"href": "https://bitbucket.org/%7Bf2fb0aad-9933-4b16-a710-d9fe1486032f%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8caca58d5b3df735099a63ec2937a66ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJH-1.png"}}, "nickname": "jhoare", "type": "user", "account_id": "557058:8ecbba08-9b4d-49d1-902f-70e85314d9ea"}, "title": "Using /tmp/gz_model.tar.gz Is not friendly for multi-user systems", "component": null, "votes": 0, "watches": 1, "content": {"raw": "We have had an issue where one user had previously ran Gazebo, which left a file: \r\n``/tmp/gz_model.tar.gz`` around. It looks like gazebo does not clean up this file after downloading a model from the web. \r\n\r\nThis was preventing any subsequent user from downloading models from the online database, as it was failing with a permissions error. (A file already existed with that name but owned by another user) We were able to resolve this by having an administrator remove the offending file. \r\n\r\nI originally thought this was caused by gazebo crashing (or being shut down) while it was downloading a model, but after checking just about every one of our shared machines had a ``/tmp/gz_model.tar.gz`` I believe that it is a more commonplace problem than I originally thought. \r\n\r\nPlease let me know if this description is unclear. ", "markup": "markdown", "html": "<p>We have had an issue where one user had previously ran Gazebo, which left a file: \n<code>/tmp/gz_model.tar.gz</code> around. It looks like gazebo does not clean up this file after downloading a model from the web. </p>\n<p>This was preventing any subsequent user from downloading models from the online database, as it was failing with a permissions error. (A file already existed with that name but owned by another user) We were able to resolve this by having an administrator remove the offending file. </p>\n<p>I originally thought this was caused by gazebo crashing (or being shut down) while it was downloading a model, but after checking just about every one of our shared machines had a <code>/tmp/gz_model.tar.gz</code> I believe that it is a more commonplace problem than I originally thought. </p>\n<p>Please let me know if this description is unclear. </p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2013-04-08T18:19:02.520883+00:00", "milestone": null, "updated_on": "2016-09-14T19:43:36.919935+00:00", "type": "issue", "id": 631}