{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/14/comments/1891599.json"}, "html": {"href": "#!/osrf/gazebo/issues/14#comment-1891599"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/14.json"}}, "type": "issue", "id": 14, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Model self_collide not working"}, "content": {"raw": "(Reply via miha...@gmail.com):\n\nit fixes it for the models that i tested.\n\ni'm just not sure if it breaks something else.\n", "markup": "creole", "html": "<p>(Reply via miha...@gmail.com):</p>\n<p>it fixes it for the models that i tested.</p>\n<p>i'm just not sure if it breaks something else.</p>\n", "type": "rendered"}, "created_on": "2012-08-30T18:50:05.327900+00:00", "user": {"display_name": "Mihai Emanuel Dolha", "uuid": "{a8a86f1d-7560-41e6-a23a-8f865506bd71}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba8a86f1d-7560-41e6-a23a-8f865506bd71%7D"}, "html": {"href": "https://bitbucket.org/%7Ba8a86f1d-7560-41e6-a23a-8f865506bd71%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8e5695199bf0735671072a706cacaf99d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMD-3.png"}}, "nickname": "mdolha", "type": "user", "account_id": "557058:69edce3a-e2d2-4e5c-80d4-8f8cf27b025f"}, "updated_on": null, "type": "issue_comment", "id": 1891599}