{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2684/comments/55624089.json"}, "html": {"href": "#!/osrf/gazebo/issues/2684#comment-55624089"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2684.json"}}, "type": "issue", "id": 2684, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Problems with running Gazebo 9 server in a Python wrapper"}, "content": {"raw": "I managed to fix this. The problem was related to handling of callbacks in the Python wrapper.\n\nAll in all, now the functionality of the cpp and Python wrappers are almost the same.", "markup": "markdown", "html": "<p>I managed to fix this. The problem was related to handling of callbacks in the Python wrapper.</p>\n<p>All in all, now the functionality of the cpp and Python wrappers are almost the same.</p>", "type": "rendered"}, "created_on": "2020-01-12T10:38:18.220777+00:00", "user": {"display_name": "Milan Vukov", "uuid": "{f7dc7621-1cb3-4887-a1fb-bc33c4af70f4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bf7dc7621-1cb3-4887-a1fb-bc33c4af70f4%7D"}, "html": {"href": "https://bitbucket.org/%7Bf7dc7621-1cb3-4887-a1fb-bc33c4af70f4%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f5c58323e480e53b39c57bc00b630b2ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMV-4.png"}}, "nickname": "Milan Vukov", "type": "user", "account_id": "5e19a55ccbf1830daa9dbacd"}, "updated_on": null, "type": "issue_comment", "id": 55624089}