{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/662/comments/3873987.json"}, "html": {"href": "#!/osrf/gazebo/issues/662#comment-3873987"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/662.json"}}, "type": "issue", "id": 662, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Occasional RaySensor_TEST failures"}, "content": {"raw": "I was trying to reproduce the bug. There is a new issue_662 branch which contains a in test/regression/ray_sensor_issue662.cc which is a shorter version of the Ray test which can trigger the segfault.\n\nI would say it's a race condition somewhere when the test finish and the stack for destructor functions is called. I wasn't unable to reproduce from looping code inside the test. It also does not happen when there is DISPLAY present. To see segfaults, you can use, from build directory:\n```\nwhile true; do DISPLAY=asedf ./test/regression/ray_sensor_issue662 2> foo ; done\n```\n\nIn my own tests, if you enable the sleep(1) at the end of the test, it's currently commented, I wasn't able to see any segfault.", "markup": "markdown", "html": "<p>I was trying to reproduce the bug. There is a new issue_662 branch which contains a in test/regression/ray_sensor_issue662.cc which is a shorter version of the Ray test which can trigger the segfault.</p>\n<p>I would say it's a race condition somewhere when the test finish and the stack for destructor functions is called. I wasn't unable to reproduce from looping code inside the test. It also does not happen when there is DISPLAY present. To see segfaults, you can use, from build directory:</p>\n<div class=\"codehilite\"><pre><span></span>while true; do DISPLAY=asedf ./test/regression/ray_sensor_issue662 2&gt; foo ; done\n</pre></div>\n\n\n<p>In my own tests, if you enable the sleep(1) at the end of the test, it's currently commented, I wasn't able to see any segfault.</p>", "type": "rendered"}, "created_on": "2013-04-25T17:37:17.225525+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "updated_on": null, "type": "issue_comment", "id": 3873987}