{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2510/comments/48537727.json"}, "html": {"href": "#!/osrf/gazebo/issues/2510#comment-48537727"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2510.json"}}, "type": "issue", "id": 2510, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Deleting model with plugin crashes gzserver"}, "content": {"raw": "I'm getting back to this issue and really need to find a fix since at the moment we have to restart Gazebo every time we want to start a new experiment with different models (which entails deleting the old models).  Here is the error I just go when trying to delete a model that includes the ray plugin:\n\ngzserver: /var/lib/jenkins/workspace/gazebo7-debbuilder/build/gazebo-7.14.0/gazebo/sensors/SensorManager.cc:551: void gazebo::sensors::SensorManager::SensorContainer::RunLoop(): Assertion `(diffTime.sec < maxSensorUpdate)&&(\"Took over 1000*max_step_size to update a sensor.\")' failed.\nAborted (core dumped)\n[gazebo-3] process has died [pid 7212, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/patrick/jr2_catkin_ws/src/jr2_testing/jr2_gazebo/worlds/gates_1_foyer_no_holes.world __name:=gazebo __log:=/home/patrick/.ros/log/5345fa70-d78f-11e8-86c8-509a4c47197c/gazebo-3.log].\nlog file: /home/patrick/.ros/log/5345fa70-d78f-11e8-86c8-509a4c47197c/gazebo-3*.log", "markup": "markdown", "html": "<p>I'm getting back to this issue and really need to find a fix since at the moment we have to restart Gazebo every time we want to start a new experiment with different models (which entails deleting the old models).  Here is the error I just go when trying to delete a model that includes the ray plugin:</p>\n<p>gzserver: /var/lib/jenkins/workspace/gazebo7-debbuilder/build/gazebo-7.14.0/gazebo/sensors/SensorManager.cc:551: void gazebo::sensors::SensorManager::SensorContainer::RunLoop(): Assertion `(diffTime.sec &lt; maxSensorUpdate)&amp;&amp;(\"Took over 1000<em>max_step_size to update a sensor.\")' failed.\nAborted (core dumped)\n[gazebo-3] process has died [pid 7212, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/patrick/jr2_catkin_ws/src/jr2_testing/jr2_gazebo/worlds/gates_1_foyer_no_holes.world <strong>name:=gazebo </strong>log:=/home/patrick/.ros/log/5345fa70-d78f-11e8-86c8-509a4c47197c/gazebo-3.log].\nlog file: /home/patrick/.ros/log/5345fa70-d78f-11e8-86c8-509a4c47197c/gazebo-3</em>.log</p>", "type": "rendered"}, "created_on": "2018-10-24T13:28:13.908242+00:00", "user": {"display_name": "Patrick Goebel", "uuid": "{72749617-947a-4e78-a1f2-2b66270949e4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B72749617-947a-4e78-a1f2-2b66270949e4%7D"}, "html": {"href": "https://bitbucket.org/%7B72749617-947a-4e78-a1f2-2b66270949e4%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/c9372162690ae792e27e271f7d1fb046d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPG-0.png"}}, "nickname": "pgoebel", "type": "user", "account_id": "5b6e45a07c14b729f2208e7e"}, "updated_on": null, "type": "issue_comment", "id": 48537727}