{"changes": {"content": {"new": "This line throws the exception:\r\n```\r\n(gdb) up\r\n#5  gazebo::common::SystemPaths::UpdateModelPaths (this=0x80a88da90 <SingletonT<gazebo::common::SystemPaths>::GetInstance()::t>)\r\n    at /usr/ports/misc/gazebo/work/osrf-gazebo-490bc3398435/gazebo/common/SystemPaths.cc:213\r\n213\t  this->InsertUnique(path.substr(pos1, path.size()-pos1), this->modelPaths);\r\n```\r\n\r\n```\r\n(gdb) p pos1\r\n$5 = 33\r\n(gdb) p path.size()\r\n$6 = 32\r\n(gdb) p path.c_str()\r\n$7 = (const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *) 0x829a2b190 \"/usr/local/share/gazebo-9/models\"\r\n```\r\n\r\nSo the arithmetic there fails and causes the overflow and the negative size is supplied to the ```path.substr``` function.", "old": "This line throws the exception:\r\n```\r\n(gdb) up\r\n#5  gazebo::common::SystemPaths::UpdateModelPaths (this=0x80a88da90 <SingletonT<gazebo::common::SystemPaths>::GetInstance()::t>)\r\n    at /usr/ports/misc/gazebo/work/osrf-gazebo-490bc3398435/gazebo/common/SystemPaths.cc:213\r\n213\t  this->InsertUnique(path.substr(pos1, path.size()-pos1), this->modelPaths);\r\n```\r\n\r\n```\r\n(gdb) p pos1\r\n$5 = 33\r\n(gdb) p path.size()\r\n$6 = 32\r\n```\r\n\r\nSo the arithmetic there fails and causes the overflow and the negative size is supplied to the ```path.substr``` function."}}, "links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2565/changes/49060948.json"}, "html": {"href": "#!/osrf/gazebo/issues/2565#comment-49060948"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2565.json"}}, "type": "issue", "id": 2565, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Missing GAZEBO_MODEL_PATH causes std::string exception and crash"}, "created_on": "2018-11-21T23:33:43.309979+00:00", "user": {"display_name": "yurivict", "uuid": "{7012cf74-23b1-4689-8f6d-63be51ab0d44}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7012cf74-23b1-4689-8f6d-63be51ab0d44%7D"}, "html": {"href": "https://bitbucket.org/%7B7012cf74-23b1-4689-8f6d-63be51ab0d44%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/501bf0c2270ceed7106969dc5e2b6f5ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsY-1.png"}}, "nickname": "yurivict", "type": "user", "account_id": "557058:683abaa1-e9c1-4591-9582-634372ed2a78"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 49060948}