{"changes": {"state": {"new": "invalid", "old": "new"}}, "links": {"self": {"href": "data/repositories/osrf/gazebo/issues/720/changes/4333115.json"}, "html": {"href": "#!/osrf/gazebo/issues/720#comment-4333115"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/720.json"}}, "type": "issue", "id": 720, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "segfault running vrc_task_2.launch"}, "created_on": "2013-06-04T15:57:51.130689+00:00", "user": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "message": {"raw": "this was running from an earlier gazebo_1.8 branch with manually merged pull requests gzlog_hang, atlas_fall and log_debug.  I'll update to released 1.8.5 and see if the error is still present.", "markup": "markdown", "html": "<p>this was running from an earlier gazebo_1.8 branch with manually merged pull requests gzlog_hang, atlas_fall and log_debug.  I'll update to released 1.8.5 and see if the error is still present.</p>", "type": "rendered"}, "type": "issue_change", "id": 4333115}